services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/video-clipping-sa.json:/app/credentials.json
    networks:
      - revmed-network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - revmed-network

networks:
  revmed-network:
    driver: bridge