steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'backend' # Set the working directory to the backend folder
  args:
  - 'build'
  - '-t'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-job'
  - '-f'
  - 'face_recognition_microservice/Dockerfile'
  - '.' # Build context is now the 'backend' directory

# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-job']

# Deploy as a Cloud Run Job (create if missing, update if exists)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      if gcloud beta run jobs describe face-recognition-job --region asia-southeast1 >/dev/null 2>&1; then
        echo "Updating existing job..."
        gcloud beta run jobs update face-recognition-job \
          --image asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-job \
          --region asia-southeast1 \
          --cpu 4 \
          --memory 16Gi \
          --tasks 1 \
          --max-retries 1
      else
        echo "Creating new job..."
        gcloud beta run jobs create face-recognition-job \
          --image asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-job \
          --region asia-southeast1 \
          --cpu 4 \
          --memory 16Gi \
          --tasks 1 \
          --max-retries 1
      fi

images:
- 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-job'