steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/face-recognition-job'
  - '-f'
  - 'face_recognition_microservice/Dockerfile'
  - '.'

# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/face-recognition-job']

# Deploy as a Cloud Run Job (create if missing, update if exists)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      if gcloud beta run jobs describe face-recognition-job --region ${_REGION} >/dev/null 2>&1; then
        echo "Updating existing job..."
        gcloud beta run jobs update face-recognition-job \
          --image ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/face-recognition-job \
          --region ${_REGION} \
          --service-account ${_SERVICE_ACCOUNT_EMAIL} \
          --cpu 4 \
          --memory 16Gi \
          --tasks 1 \
          --max-retries 1
      else
        echo "Creating new job..."
        gcloud beta run jobs create face-recognition-job \
          --image ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/face-recognition-job \
          --region ${_REGION} \
          --service-account ${_SERVICE_ACCOUNT_EMAIL} \
          --cpu 4 \
          --memory 16Gi \
          --tasks 1 \
          --max-retries 1
      fi

images:
- '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/face-recognition-job'
