steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-service', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-service']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'face-recognition-service'
  - '--image'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-service'
  - '--region'
  - 'asia-southeast1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--cpu'
  - '4'
  - '--memory'
  - '16Gi'
  - '--set-env-vars'
  - 'BACKEND_URL=https://backend-dvgm2r6s4q-as.a.run.app'
images:
- 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/revmed-app/face-recognition-service'